/**
 * Zod schemas for validating OpenAI borrower extraction responses
 */

import { z } from 'zod';

/**
 * Source reference schema - ensures traceability for every extracted field
 */
export const ExtractionSourceReferenceSchema = z.object({
  documentId: z.string().uuid('Document ID must be a valid UUID'),
  fileName: z.string().min(1, 'File name is required'),
  chunkId: z.string().min(1, 'Chunk ID is required'),
  quote: z.string().min(1, 'Evidence quote is required')
});

/**
 * Generic extracted field schema with full traceability
 */
export const ExtractedFieldSchema = <T extends z.ZodTypeAny>(valueSchema: T) =>
  z.object({
    value: valueSchema,
    confidence: z.number().min(0).max(1, 'Confidence must be between 0 and 1'),
    sourceDocumentId: z.string().uuid('Source document ID must be a valid UUID'),
    sourcePage: z.number().int().positive('Source page must be a positive integer'),
    evidenceQuote: z.string().min(1, 'Evidence quote is required'),
    boundingBox: z.tuple([z.number(), z.number(), z.number(), z.number()]).optional(),
    extractedAt: z.string().datetime().or(z.date()).optional(),
    notes: z.string().optional()
  });

/**
 * Extracted address schema
 */
export const ExtractedAddressSchema = z.object({
  street: ExtractedFieldSchema(z.string().min(1)),
  city: ExtractedFieldSchema(z.string().min(1)),
  state: ExtractedFieldSchema(z.string().min(1)),
  zipCode: ExtractedFieldSchema(z.string().min(1)),
  country: ExtractedFieldSchema(z.string().min(1)).optional()
});

/**
 * Income type enum
 */
export const IncomeTypeSchema = z.enum([
  'W2',
  'SELF_EMPLOYMENT',
  'RENTAL',
  'INVESTMENT',
  'RETIREMENT',
  'SOCIAL_SECURITY',
  'OTHER'
]);

/**
 * Income frequency enum
 */
export const IncomeFrequencySchema = z.enum([
  'HOURLY',
  'WEEKLY',
  'BIWEEKLY',
  'SEMIMONTHLY',
  'MONTHLY',
  'QUARTERLY',
  'ANNUAL'
]);

/**
 * Income history item schema
 */
export const IncomeHistoryItemSchema = z.object({
  employer: ExtractedFieldSchema(z.string().min(1)),
  jobTitle: ExtractedFieldSchema(z.string().min(1)).optional(),
  incomeType: ExtractedFieldSchema(IncomeTypeSchema),
  frequency: ExtractedFieldSchema(IncomeFrequencySchema),
  grossAmount: ExtractedFieldSchema(z.number().positive()),
  netAmount: ExtractedFieldSchema(z.number().positive()).optional(),
  startDate: ExtractedFieldSchema(z.string()),  // ISO date string or date description
  endDate: ExtractedFieldSchema(z.string()).optional(),
  isCurrent: ExtractedFieldSchema(z.boolean()),
  ytdEarnings: ExtractedFieldSchema(z.number().nonnegative()).optional(),
  taxYear: ExtractedFieldSchema(z.number().int().min(1900).max(2100)).optional()
});

/**
 * Complete borrower extraction schema
 * Validates the structure returned by OpenAI
 */
export const BorrowerExtractionSchema = z.object({
  id: z.string().uuid().optional(),  // May be generated by system
  fullName: ExtractedFieldSchema(z.string().min(1)),
  firstName: ExtractedFieldSchema(z.string().min(1)).optional(),
  middleName: ExtractedFieldSchema(z.string().min(1)).optional(),
  lastName: ExtractedFieldSchema(z.string().min(1)).optional(),
  ssn: ExtractedFieldSchema(z.string().min(1)).optional(),
  dateOfBirth: ExtractedFieldSchema(z.string()).optional(),
  phoneNumber: ExtractedFieldSchema(z.string().min(1)).optional(),
  alternatePhoneNumber: ExtractedFieldSchema(z.string().min(1)).optional(),
  email: ExtractedFieldSchema(z.string().email()).optional(),
  currentAddress: ExtractedAddressSchema.optional(),
  previousAddresses: z.array(ExtractedAddressSchema).optional(),
  incomeHistory: ExtractedFieldSchema(z.array(IncomeHistoryItemSchema)).optional(),
  accountNumbers: z.array(ExtractedFieldSchema(z.string().min(1))).optional(),
  loanNumbers: z.array(ExtractedFieldSchema(z.string().min(1))).optional(),
  createdAt: z.string().datetime().or(z.date()).optional(),
  updatedAt: z.string().datetime().or(z.date()).optional(),
  documentIds: z.array(z.string().uuid()).optional()
});

/**
 * Schema for OpenAI response containing multiple borrowers
 */
export const OpenAIExtractionResponseSchema = z.object({
  borrowers: z.array(BorrowerExtractionSchema)
});

/**
 * TypeScript types inferred from schemas
 */
export type ExtractedFieldType<T> = z.infer<ReturnType<typeof ExtractedFieldSchema<z.ZodType<T>>>>;
export type ExtractedAddressType = z.infer<typeof ExtractedAddressSchema>;
export type IncomeHistoryItemType = z.infer<typeof IncomeHistoryItemSchema>;
export type BorrowerExtractionType = z.infer<typeof BorrowerExtractionSchema>;
export type OpenAIExtractionResponseType = z.infer<typeof OpenAIExtractionResponseSchema>;
